trigger:
  branches:
    include:
    - feature/*
    - master

resources:
  - repo: self

variables:
  - group: tempaast-ui


stages:
- stage: Build
  jobs:
  - job: Build
    displayName: Build 
    pool:
      vmImage: 'windows-2019'
      timeoutInMinutes: 10
    steps:
      - checkout: self
        persistCredentials: true

      - bash: |
          npm install
        displayName: "NPM Install"

      - bash: |
          npm run build

      - task: ArchiveFiles@2
        displayName: Collect Build
        inputs:
          rootFolderOrFile: 'build' 
          includeRootFolder: true 
          archiveType: 'zip' 
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip' 
          replaceExistingArchive: true 
      
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)' 
          artifactName: '$(Build.BuildId).zip' 
          publishLocation: 'filePath' # Options: container, filePath
          targetPath: $(System.DefaultWorkingDirectory)

  - job: Deploy
    displayName: Deploy
    dependsOn: 'Build'
    pool:
      vmImage: 'windows-2019'
      timeoutInMinutes: 10
    steps:
      - task: ExtractFiles@1
        displayName: Extract Build Artifact
        inputs:
          archiveFilePatterns: '$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip' 
          destinationFolder: $(System.DefaultWorkingDirectory)/deploy
          cleanDestinationFolder: true 
          overwriteExistingFiles: false
      
      - task: AzureCLI@2
        displayName: Deploy Container
        inputs:
          azureSubscription: dwtech
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az storage blob upload-batch -s $(System.DefaultWorkingDirectory)/deploy -d '$web' --account-name $(storageAccountName) --account-key $(containerKey)
              